### ISSUE TITLE
STS service failed with HTTP status code 403

### ISSUE THREAD

**Issue by gbakthavatchalam** [minio/minio-java#1252]
My environment:

```
containers:
        - name: minio
          image: quay.io/minio/minio:latest
          args:
            - gateway
            - azure
            - '--console-address'
            - ':9001'
```

Temporary credentials obtained with root user returns 403 forbidden when used from spark.

So., as per the steps mentioned here https://github.com/minio/minio-java/issues/1164, I created a non root user with policy `consoleAdmin` and no groups attached

But I get 403 forbidden when I initialise the `AssumeRoleProvider` with the non root user credentials.

My Policy JSON below

```json
{
    "Version": "2012-10-17",
    "Statement": [
      {
        "Sid": "random alphanumeric",
        "Effect": "Allow",
        "Action": ["s3:GetObject"],
        "Resource": ["arn:aws:s3:::mybucket/path", "arn:aws:s3:::mybucket/path/*"]
      }
    ]
}
```

My code below

```
val assumeRoleProvider = new AssumeRoleProvider(
      "http://localhost:9000"
      "nonroot",
      "password",
      60 * 60,
      <policy>,
      null,
      null,
      null,
      null,
      null
    )

```

Error message below

```
java.security.ProviderException: STS service failed with HTTP status code 403
	at io.minio.credentials.AssumeRoleBaseProvider.fetch(AssumeRoleBaseProvider.java:86)
```

@balamurugana , can you please suggest what might be going wrong here
