### ISSUE TITLE
STS service failed with HTTP status code 400

### ISSUE THREAD

**Issue by gredwhite** [minio/minio-java#1400]
my `docker-compose` file looks like this:

```
version: '3.6'

services:
 ...
  minio:
    container_name: minio
    image: bitnami/minio:2022.11.17-debian-11-r0
    volumes:
      - minio-data:/data
    ports:
      - 9000:9000
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio
      - MINIO_DEFAULT_BUCKETS=mybucket,qwerty
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s

volumes:
  minio-data:
  ```
  
  minio dependency is:
  
  ```
  <dependency>
      <groupId>io.minio</groupId>
      <artifactId>minio</artifactId>
      <version>8.4.5</version>
    </dependency>
```
  
  
  In my java code I try to execute following code:
  
 ` minioClient.bucketExists("mybucket").build())`
 
 but it fails because of failed request to minio:
 
 
![image](https://user-images.githubusercontent.com/6998637/209156872-c3436ef3-85fb-4627-ab3a-2b361df00093.png)

  
  
  request to minio(inside https://github.com/minio/minio-java/blob/0048fdd5b23bf86fd2100fcc0b5b2df69d47c1b9/api/src/main/java/io/minio/credentials/AssumeRoleBaseProvider.java#L83 ) look like this:
  
  
![image](https://user-images.githubusercontent.com/6998637/209157419-5320ba86-5aaf-47a2-9b34-3af5fccbe47a.png)

How can I fix it ?

P.S.
Minio logs don't have any information about the issue. It is sad.
