### ISSUE TITLE
SSLHandshakeException When Connecting to MinIO Service in Kubernetes Environment

### ISSUE THREAD

**Issue by TartanLeGrand** [minio/minio-java#1542]
Hello,

I'm encountering an `SSLHandshakeException` error when attempting to connect to a MinIO service deployed in a Kubernetes cluster using the `minio/minio-java` client. Below are the details of my configuration and the error message.

**Environment**:
- Kubernetes with a MinIO operator configured
- MinIO Java client version: [specify the version if known]

**MinIO Tenant Configuration**:
I have set up a MinIO tenant in my Kubernetes cluster with the following configuration (sensitive details anonymized):

```yaml
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minio-tenant
spec:
  pools:
    - servers: 4
      name: pool-0
      volumesPerServer: 2
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
      containerSecurityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
  requestAutoCert: true
  ```
  
**Error Message:**
When using the MinIO Java client to upload a file, I receive the following SSL handshake error:

```lua
javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
...
```

**Client Configuration:**
I am using the following MinIO client configuration in my Java application:

```java
MinioClient minioClient = MinioClient.builder()
    .endpoint("my-conf.svc", 9000, true)
    .credentials("Q3AM3UQ867SPQQA43P2F", "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG")
    .build();
```

**Observations:**
- When attempting to connect to https://my-conf.svc:9000, I encounter a certificate error.
- A similar issue occurs when trying to connect to https://my-conf.svc:443.
- Connecting to https://my-conf.svc appears to accept the certificate, but it tries to connect to the IP on port 443 instead.

**Request:**
Could you please assist in resolving this SSLHandshakeException issue? Any guidance on configuring the MinIO Java client or the Kubernetes environment to successfully establish a secure connection would be greatly appreciated.

Thank you for your help.
