### ISSUE TITLE
NullPointerException accessing Item.lastModified()

### ISSUE THREAD

**Issue by hwaite** [minio/minio-java#1606]
See #1605. NullPointerException on accessing `io.minio.messages.Item.lastModified()` against item retrieved from `io.minio.MinioClient.listObjects(io.minio.ListObjectsArgs)`. Error occurs if the object prefix represents a pseudo-folder (i.e. there are object keys that follow prefix with a slash):

```java
final String bucket = "buck";
try (
    MinioClient client = MinioClient.builder()
        .endpoint("%s:%s".formatted(MINIO_HOST, MINIO_PORT))
        .credentials(MINIO_USERNAME, MINIO_PASSWORD)
        .build()
) {
    client.makeBucket(
        MakeBucketArgs.builder()
            .bucket(bucket)
            .build()
    );

    for (String str : List.of("foo/bar", "foo/car")) {
        final long size = str.length();
        client.putObject(
            PutObjectArgs.builder()
                .bucket(bucket)
                .object(str)
                .stream(
                    new ByteArrayInputStream(str.getBytes(StandardCharsets.UTF_8)),
                    size,
                    -1
                )
                .build()

        );
    }

    for (
        Result<Item> r :
        client.listObjects(
            ListObjectsArgs.builder()
                .bucket(bucket)
                .prefix("foo")
                .build()
        )
    ) {
        System.out.println(r.get().lastModified());
    }
}
```

**Comment by balamurugana** [comment]
Please share the object storage server detail

**Comment by hwaite** [comment]
Nothing special:

```yaml
services:
  minio:
    image: 'minio/minio:latest'
    hostname: minio
    container_name: minio-test
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server --console-address ":9001" /data

volumes:
  minio-data:
    driver: local
```
